version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./web/nginx.conf:/etc/nginx/nginx.conf"
      - "files:/usr/share/files"
    restart: unless-stopped
    depends_on:
      - sftp
  sftp:
    build:
      context: .
      dockerfile: ./sftp/Dockerfile
    ports:
      - "22:22"
    volumes:
      - "files:/home/"
    restart: unless-stopped

volumes:
  files:
